export const SEGWIT_INPUT_WEIGHT_UNIT = 272;
export const SEGWIT_OUTPUT_WEIGHT_UNIT = 124;
export const CONFIRMATION_TARGET = 6;
export const TAPROOT_INPUT_WEIGHT_UNIT = 230;
export const TAPROOT_OUTPUT_WEIGHT_UNIT = 172;
export const MINIMUM_BTC_FOR_NATIVE_SEGWIT_OUTPUT = 294n;
export const MINIMUM_BTC_FOR_TAPROOT_OUTPUT = 330n;
export const GET_BOX_API_LIMIT = 10;
