image: $GITLAB_CI_IMAGE

default:
  interruptible: true

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /push/'
      when: always
    - when: never

include:
  - component: $CI_SERVER_FQDN/${ROOT_COMPONENT}

    inputs:
      install_cache_paths:
        - node_modules
        - apps/*/node_modules
        - packages/*/node_modules
        - networks/*/node_modules
        - wallets/*/node_modules
      build_cache_paths:
        - node_modules
        - apps/*/node_modules
        - networks/*/node_modules
        - networks/*/dist
        - packages/*/node_modules
        - packages/*/dist
        - wallets/*/node_modules
        - wallets/*/dist
      build_script: 
        - npm run build:mono-packages
      enable_ci_child: true
