import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  workspaces: {},
  ignoreBinaries: [
    'changeset',
    'eslint',
    'husky',
    'knip',
    'lint-staged',
    'next',
    'prettier',
    'tauri',
    'tsc',
    'tsx',
    'typeorm',
    'vite',
  ],
  ignore: ['**/node_modules/', '**/dist/', '**/.next/'],
  ignoreDependencies: [
    '@emotion/react',
    '@emotion/styled',
    '@mui/material',
    '@next/eslint-plugin-next',
    '@rosen-bridge/abstract-logger',
    '@rosen-bridge/abstract-scanner',
    '@rosen-bridge/address-codec',
    '@rosen-bridge/bitcoin-observation-extractor',
    '@rosen-bridge/bitcoin-scanner',
    '@rosen-bridge/cardano-scanner',
    '@rosen-bridge/ergo-scanner',
    '@rosen-bridge/evm-observation-extractor',
    '@rosen-bridge/evm-scanner',
    '@rosen-bridge/extended-typeorm',
    '@rosen-bridge/handshake-rpc-observation-extractor',
    '@rosen-bridge/handshake-rpc-scanner',
    '@rosen-bridge/health-check',
    '@rosen-bridge/json-bigint',
    '@rosen-bridge/log-level-check',
    '@rosen-bridge/minimum-fee',
    '@rosen-bridge/scanner-interfaces',
    '@rosen-bridge/scanner-sync-check',
    '@rosen-bridge/service-manager',
    '@rosen-bridge/tokens',
    '@rosen-bridge/watcher-data-extractor',
    '@tauri-apps/cli',
    '@types/react',
    '@types/react-dom',
    '@vitest/runner',
    'eslint',
    'eslint-config-next',
    'husky',
    'lint-staged',
    'pg',
    'prettier',
    'react-dom',
  ],
};

export default config;
