image: node:22.18.0

default:
  interruptible: true

workflow:
  auto_cancel:
    on_job_failure: all

stages:
  - ci

variables:
  npm_config_cache: '${CI_PROJECT_DIR}/.npm'
  NPM_VERSION: '11.6.2'

before_script:
  - npm i -g npm@${NPM_VERSION}

knip:
  stage: ci
  cache:
    key: ${CI_COMMIT_REF_NAME}
    policy: pull
    paths:
      - node_modules
      - .npm
  script:
    - npx knip --dependencies

type_check:
  stage: ci
  cache:
    key: ${CI_COMMIT_REF_NAME}
    policy: pull
    paths:
      - node_modules
      - apps/*/node_modules
      - packages/*/node_modules
      - packages/*/dist
      - wallets/*/node_modules
      - wallets/*/dist
      - networks/*/node_modules
      - networks/*/dist
      - .npm
  script:
    - npm run type-check

lint:
  stage: ci
  cache:
    key: ${CI_COMMIT_REF_NAME}
    policy: pull
    paths:
      - node_modules
      - .npm
  script:
    - npm run lint:check

unit_tests:
  stage: ci
  cache:
    key: ${CI_COMMIT_REF_NAME}
    policy: pull
    paths:
      - node_modules
      - apps/*/node_modules
      - apps/*/dist
      - networks/*/node_modules
      - networks/*/dist
      - packages/*/node_modules
      - packages/*/dist
      - wallets/*/node_modules
      - wallets/*/dist
      - .npm
  script:
    - npm run coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: 'coverage/cobertura-coverage.xml'

changeset:
  stage: ci
  cache:
    key: ${CI_COMMIT_REF_NAME}
    policy: pull
    paths:
      - node_modules
      - .npm
  before_script:
    - git fetch origin dev
    - npm i -g npm@${NPM_VERSION}
  script:
    - npx changeset status --since=origin/dev
