import { RosenTokens } from '@rosen-bridge/tokens';

export const tokenMapData: RosenTokens = [
  {
    ergo: {
      tokenId:
        '1111111111111111111111111111111111111111111111111111111111111111',
      extra: {},
      name: 'test token1',
      decimals: 0,
      type: 'tokenType',
      residency: 'native',
    },
    cardano: {
      tokenId: 'policyId2.assetName2',
      extra: {
        policyId: 'policyId2',
        assetName: 'assetName2',
      },
      name: 'asset1',
      decimals: 0,
      type: 'tokenType',
      residency: 'wrapped',
    },
  },
  {
    ergo: {
      tokenId:
        '2222222222222222222222222222222222222222222222222222222222222222',
      extra: {},
      name: 'test token2',
      decimals: 0,
      type: 'tokenType',
      residency: 'native',
    },
    cardano: {
      tokenId: 'policyId2.assetName2',
      extra: {
        policyId: 'policyId2',
        assetName: 'assetName2',
      },
      name: 'asset2',
      decimals: 0,
      type: 'tokenType',
      residency: 'wrapped',
    },
  },
  {
    ergo: {
      tokenId: 'tokenId',
      extra: {},
      name: 'test token3',
      decimals: 0,
      type: 'tokenType',
      residency: 'wrapped',
    },
    cardano: {
      tokenId: 'policyId3.assetName3',
      extra: {
        policyId: 'policyId3',
        assetName: 'assetName3',
      },
      name: 'asset3',
      decimals: 0,
      type: 'tokenType',
      residency: 'native',
    },
  },
];

export enum ChainEnum {
  ERGO = 'ergo',
}

export const tokenData = [
  {
    id: 'token-1',
    name: 'Token 1',
    decimal: 0,
    significantDecimal: 0,
    isNative: false,
    chain: ChainEnum.ERGO,
  },
  {
    id: 'token-2',
    name: 'Token 2',
    decimal: 0,
    significantDecimal: 0,
    isNative: false,
    chain: ChainEnum.ERGO,
  },
];

export const eventTriggerData = [
  {
    eventId: 'u1',
    boxId: 'b1',
    block: 'blk1',
    height: 100,
    extractor: 'ext1',
    fromChain: 'ergo',
    toChain: 'cardano',
    txId: 'tx1',
    fromAddress: 'addr1',
    toAddress: 'addr2',
    amount: '10',
    bridgeFee: '1',
    networkFee: '0.1',
    sourceChainTokenId: 't1',
    sourceChainHeight: 100,
    targetChainTokenId: 't2',
    sourceTxId: 'stx1',
    sourceBlockId: 'sb1',
    spendBlock: 'sblk1',
    spendHeight: 110,
    spendTxId: 'spendtx1',
    result: 'Success',
    paymentTxId: 'ptx1',
    WIDsCount: 1,
    WIDsHash: 'hash1',
    serialized: '{}',
  },
  {
    eventId: 'u2',
    boxId: 'b2',
    block: 'blk2',
    height: 101,
    extractor: 'ext2',
    fromChain: 'ergo',
    toChain: 'cardano',
    txId: 'tx2',
    fromAddress: 'addr1',
    toAddress: 'addr2',
    amount: '5',
    bridgeFee: '0.5',
    networkFee: '0.05',
    sourceChainTokenId: 't1',
    sourceChainHeight: 101,
    targetChainTokenId: 't2',
    sourceTxId: 'stx2',
    sourceBlockId: 'sb2',
    spendBlock: 'sblk2',
    spendHeight: 111,
    spendTxId: 'spendtx2',
    result: 'Success',
    paymentTxId: 'ptx2',
    WIDsCount: 1,
    WIDsHash: 'hash2',
    serialized: '{}',
  },
  {
    eventId: 'u3',
    boxId: 'b3',
    block: 'blk3',
    height: 102,
    extractor: 'ext3',
    fromChain: 'ergo',
    toChain: 'cardano',
    txId: 'tx3',
    fromAddress: 'addr3',
    toAddress: 'addr4',
    amount: '2',
    bridgeFee: '0.2',
    networkFee: '0.02',
    sourceChainTokenId: 't1',
    sourceChainHeight: 102,
    targetChainTokenId: 't2',
    sourceTxId: 'stx3',
    sourceBlockId: 'sb3',
    spendBlock: 'sblk3',
    spendHeight: 112,
    spendTxId: 'spendtx3',
    result: 'Success',
    paymentTxId: 'ptx3',
    WIDsCount: 1,
    WIDsHash: 'hash3',
    serialized: '{}',
  },
  {
    eventId: 'u4',
    boxId: 'b4',
    block: 'blk4',
    height: 103,
    extractor: 'ext4',
    fromChain: 'ergo',
    toChain: 'cardano',
    txId: 'tx4',
    fromAddress: 'addrX',
    toAddress: 'addrY',
    amount: '7',
    bridgeFee: '0.7',
    networkFee: '0.07',
    sourceChainTokenId: 't1',
    sourceChainHeight: 103,
    targetChainTokenId: 't2',
    sourceTxId: 'stx4',
    sourceBlockId: 'sb4',
    spendBlock: 'sblk4',
    spendHeight: 113,
    spendTxId: 'spendtx4',
    result: 'Processing',
    paymentTxId: 'ptx4',
    WIDsCount: 1,
    WIDsHash: 'hash4',
    serialized: '{}',
  },
];
