/* eslint-disable @typescript-eslint/no-explicit-any */
import { RosenTokens } from '@rosen-bridge/tokens';

import { WatcherCountConfig } from '../lib';

export const tokenMapData: RosenTokens = [
  {
    ergo: {
      tokenId:
        '1111111111111111111111111111111111111111111111111111111111111111',
      extra: {},
      name: 'test token1',
      decimals: 0,
      type: 'tokenType',
      residency: 'native',
    },
    cardano: {
      tokenId: 'policyId2.assetName2',
      extra: {
        policyId: 'policyId2',
        assetName: 'assetName2',
      },
      name: 'asset1',
      decimals: 0,
      type: 'tokenType',
      residency: 'wrapped',
    },
  },
  {
    ergo: {
      tokenId:
        '2222222222222222222222222222222222222222222222222222222222222222',
      extra: {},
      name: 'test token2',
      decimals: 0,
      type: 'tokenType',
      residency: 'native',
    },
    cardano: {
      tokenId: 'policyId2.assetName2',
      extra: {
        policyId: 'policyId2',
        assetName: 'assetName2',
      },
      name: 'asset2',
      decimals: 0,
      type: 'tokenType',
      residency: 'wrapped',
    },
  },
  {
    ergo: {
      tokenId: 'tokenId',
      extra: {},
      name: 'test token3',
      decimals: 0,
      type: 'tokenType',
      residency: 'wrapped',
    },
    cardano: {
      tokenId: 'policyId3.assetName3',
      extra: {
        policyId: 'policyId3',
        assetName: 'assetName3',
      },
      name: 'asset3',
      decimals: 0,
      type: 'tokenType',
      residency: 'native',
    },
  },
];

export const lockedAssetsTestData = {
  test1: {
    tokenRepo: [
      {
        id: 'token-1',
        name: 'Token 1',
        decimal: 0,
        significantDecimal: 0,
        isNative: false,
        chain: 'ergo' as const,
        ergoSideTokenId: 'ergo-token-1',
        isResident: true,
      },
      {
        id: 'token-2',
        name: 'Token 2',
        decimal: 0,
        significantDecimal: 0,
        isNative: false,
        chain: 'ergo' as const,
        ergoSideTokenId: 'ergo-token-2',
        isResident: true,
      },
    ],
    lockedAssetRepo: [
      { address: 'addr1', tokenId: 'token-1', amount: BigInt(10) },
      { address: 'addr2', tokenId: 'token-1', amount: BigInt(7) },
      { address: 'addr3', tokenId: 'token-1', amount: BigInt(3) },

      { address: 'addr4', tokenId: 'token-2', amount: BigInt(5) },
      { address: 'addr5', tokenId: 'token-2', amount: BigInt(2) },
    ],
    tokenPriceRepo: [
      {
        tokenId: 'token-1',
        price: 10,
        timestamp: 2_000,
      },
      {
        tokenId: 'token-2',
        price: 4,
        timestamp: 2_000,
      },
      {
        tokenId: 'token-2',
        price: 3,
        timestamp: 3_000,
      },
    ],
  },

  test2: {
    tokenRepo: [
      {
        id: 'token-1',
        name: 'Token 1',
        decimal: 0,
        significantDecimal: 0,
        isNative: false,
        chain: 'ergo' as const,
        ergoSideTokenId: 'ergo-token-1',
        isResident: true,
      },
    ],
    lockedAssetRepo: [
      {
        address: 'addr1',
        tokenId: 'token-1',
        amount: BigInt(10),
      },
    ],
  },
};

export const eventCountTestData = {
  test1: {
    eventTriggerRepo: [
      {
        eventId: 'event1',
        boxId: 'box1',
        block: 'block1',
        height: 100,
        extractor: 'ext1',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx1',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '100',
        bridgeFee: '1',
        networkFee: '0.1',
        sourceChainTokenId: 'token1',
        sourceChainHeight: 100,
        targetChainTokenId: 'token2',
        sourceTxId: 'sourceTx1',
        sourceBlockId: 'sourceBlock1',
        spendBlock: 'block1',
        spendHeight: 110,
        spendTxId: 'spendTx1',
        result: 'successful',
        paymentTxId: 'paymentTx1',
        WIDsCount: 1,
        WIDsHash: 'hash1',
        serialized: '{}',
      },
      {
        eventId: 'event2',
        boxId: 'box2',
        block: 'block2',
        height: 101,
        extractor: 'ext2',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx2',
        fromAddress: 'addr2',
        toAddress: 'addr3',
        amount: '200',
        bridgeFee: '2',
        networkFee: '0.2',
        sourceChainTokenId: 'token3',
        sourceChainHeight: 101,
        targetChainTokenId: 'token4',
        sourceTxId: 'sourceTx2',
        sourceBlockId: 'sourceBlock2',
        spendBlock: 'block2',
        spendHeight: 111,
        spendTxId: 'spendTx2',
        result: 'fraud',
        paymentTxId: 'paymentTx2',
        WIDsCount: 1,
        WIDsHash: 'hash2',
        serialized: '{}',
      },
      {
        eventId: 'event3',
        boxId: 'box3',
        block: 'block3',
        height: 102,
        extractor: 'ext3',
        fromChain: 'cardano',
        toChain: 'ergo',
        txId: 'tx3',
        fromAddress: 'addr3',
        toAddress: 'addr4',
        amount: '300',
        bridgeFee: '3',
        networkFee: '0.3',
        sourceChainTokenId: 'token5',
        sourceChainHeight: 102,
        targetChainTokenId: 'token6',
        sourceTxId: 'sourceTx3',
        sourceBlockId: 'sourceBlock3',
        spendBlock: 'block3',
        spendHeight: 112,
        spendTxId: 'spendTx3',
        result: 'successful',
        paymentTxId: 'paymentTx3',
        WIDsCount: 1,
        WIDsHash: 'hash3',
        serialized: '{}',
      },
      {
        eventId: 'event4',
        boxId: 'box4',
        block: 'block4',
        height: 103,
        extractor: 'ext4',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx4',
        fromAddress: 'addr4',
        toAddress: 'addr5',
        amount: '400',
        bridgeFee: '4',
        networkFee: '0.4',
        sourceChainTokenId: 'token7',
        sourceChainHeight: 103,
        targetChainTokenId: 'token8',
        sourceTxId: 'sourceTx4',
        sourceBlockId: 'sourceBlock4',
        spendBlock: 'block4',
        spendHeight: 113,
        spendTxId: 'spendTx4',
        result: 'pending',
        paymentTxId: 'paymentTx4',
        WIDsCount: 1,
        WIDsHash: 'hash4',
        serialized: '{}',
      },
    ],
    expectedResults: {
      totalCount: 3,
      eventCounts: [
        {
          status: 'successful',
          fromChain: 'ergo',
          toChain: 'cardano',
          count: 1,
        },
        { status: 'fraud', fromChain: 'ergo', toChain: 'cardano', count: 1 },
        {
          status: 'successful',
          fromChain: 'cardano',
          toChain: 'ergo',
          count: 1,
        },
      ],
      totalMetricValue: '3',
    },
  },

  test2: {
    eventCountRepo: [
      {
        status: 'successful',
        fromChain: 'ergo',
        toChain: 'cardano',
        eventCount: 5,
        lastProcessedHeight: 100,
      },
    ],
    metricRepo: [
      {
        key: 'event_count_total',
        value: '5',
        updatedAt: 1_000,
      },
    ],
    expectedResults: {
      totalCount: 0,
      eventCounts: [],
      totalMetricValue: '5',
    },
  },

  test3: {
    eventTriggerRepo: [
      {
        eventId: 'event1',
        boxId: 'box1',
        block: 'block1',
        height: 100,
        extractor: 'ext1',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx1',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '100',
        bridgeFee: '1',
        networkFee: '0.1',
        sourceChainTokenId: 'token1',
        sourceChainHeight: 100,
        targetChainTokenId: 'token2',
        sourceTxId: 'sourceTx1',
        sourceBlockId: 'sourceBlock1',
        spendBlock: 'block1',
        spendHeight: 110,
        spendTxId: 'spendTx1',
        result: 'successful',
        paymentTxId: 'paymentTx1',
        WIDsCount: 1,
        WIDsHash: 'hash1',
        serialized: '{}',
      },
      {
        eventId: 'event2',
        boxId: 'box2',
        block: 'block2',
        height: 101,
        extractor: 'ext2',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx2',
        fromAddress: 'addr2',
        toAddress: 'addr3',
        amount: '200',
        bridgeFee: '2',
        networkFee: '0.2',
        sourceChainTokenId: 'token3',
        sourceChainHeight: 101,
        targetChainTokenId: 'token4',
        sourceTxId: 'sourceTx2',
        sourceBlockId: 'sourceBlock2',
        spendBlock: 'block2',
        spendHeight: 115,
        spendTxId: 'spendTx2',
        result: 'successful',
        paymentTxId: 'paymentTx2',
        WIDsCount: 1,
        WIDsHash: 'hash2',
        serialized: '{}',
      },
      {
        eventId: 'event3',
        boxId: 'box3',
        block: 'block3',
        height: 102,
        extractor: 'ext3',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx3',
        fromAddress: 'addr3',
        toAddress: 'addr4',
        amount: '300',
        bridgeFee: '3',
        networkFee: '0.3',
        sourceChainTokenId: 'token5',
        sourceChainHeight: 102,
        targetChainTokenId: 'token6',
        sourceTxId: 'sourceTx3',
        sourceBlockId: 'sourceBlock3',
        spendBlock: 'block3',
        spendHeight: 120,
        spendTxId: 'spendTx3',
        result: 'successful',
        paymentTxId: 'paymentTx3',
        WIDsCount: 1,
        WIDsHash: 'hash3',
        serialized: '{}',
      },
    ],
    expectedResults: {
      totalCount: 3,
      eventCounts: [
        {
          status: 'successful',
          fromChain: 'ergo',
          toChain: 'cardano',
          count: 3,
        },
      ],
      totalMetricValue: '3',
    },
  },

  test4: {
    eventTriggerRepo: [
      {
        eventId: 'event1',
        boxId: 'box1',
        block: 'block1',
        height: 105,
        extractor: 'ext1',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx1',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '100',
        bridgeFee: '1',
        networkFee: '0.1',
        sourceChainTokenId: 'token1',
        sourceChainHeight: 105,
        targetChainTokenId: 'token2',
        sourceTxId: 'sourceTx1',
        sourceBlockId: 'sourceBlock1',
        spendBlock: 'block1',
        spendHeight: 115,
        spendTxId: 'spendTx1',
        result: 'successful',
        paymentTxId: 'paymentTx1',
        WIDsCount: 1,
        WIDsHash: 'hash1',
        serialized: '{}',
      },
      {
        eventId: 'event2',
        boxId: 'box2',
        block: 'block2',
        height: 106,
        extractor: 'ext2',
        fromChain: 'cardano',
        toChain: 'ergo',
        txId: 'tx2',
        fromAddress: 'addr2',
        toAddress: 'addr3',
        amount: '200',
        bridgeFee: '2',
        networkFee: '0.2',
        sourceChainTokenId: 'token3',
        sourceChainHeight: 106,
        targetChainTokenId: 'token4',
        sourceTxId: 'sourceTx2',
        sourceBlockId: 'sourceBlock2',
        spendBlock: 'block2',
        spendHeight: 116,
        spendTxId: 'spendTx2',
        result: 'fraud',
        paymentTxId: 'paymentTx2',
        WIDsCount: 1,
        WIDsHash: 'hash2',
        serialized: '{}',
      },
    ],
    eventCountRepo: [
      {
        status: 'successful',
        fromChain: 'ergo',
        toChain: 'cardano',
        eventCount: 5,
        lastProcessedHeight: 100,
      },
      {
        status: 'fraud',
        fromChain: 'cardano',
        toChain: 'ergo',
        eventCount: 2,
        lastProcessedHeight: 100,
      },
    ],
    metricRepo: [
      {
        key: 'event_count_total',
        value: '7',
        updatedAt: 1_000,
      },
    ],
    expectedResults: {
      totalCount: 2,
      eventCounts: [
        {
          status: 'successful',
          fromChain: 'ergo',
          toChain: 'cardano',
          count: 6,
        },
        { status: 'fraud', fromChain: 'cardano', toChain: 'ergo', count: 3 },
      ],
      totalMetricValue: '9',
    },
  },

  test5: {
    eventTriggerRepo: [
      {
        eventId: 'event1',
        boxId: 'box1',
        block: 'block1',
        height: 90,
        extractor: 'ext1',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx1',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '100',
        bridgeFee: '1',
        networkFee: '0.1',
        sourceChainTokenId: 'token1',
        sourceChainHeight: 90,
        targetChainTokenId: 'token2',
        sourceTxId: 'sourceTx1',
        sourceBlockId: 'sourceBlock1',
        spendBlock: 'block1',
        spendHeight: 95,
        spendTxId: 'spendTx1',
        result: 'successful',
        paymentTxId: 'paymentTx1',
        WIDsCount: 1,
        WIDsHash: 'hash1',
        serialized: '{}',
      },
    ],
    eventCountRepo: [
      {
        status: 'successful',
        fromChain: 'ergo',
        toChain: 'cardano',
        eventCount: 5,
        lastProcessedHeight: 100,
      },
    ],
    metricRepo: [
      {
        key: 'event_count_total',
        value: '5',
        updatedAt: 1_000,
      },
    ],
    expectedResults: {
      totalCount: 0,
      eventCounts: [
        {
          status: 'successful',
          fromChain: 'ergo',
          toChain: 'cardano',
          count: 5,
        },
      ],
      totalMetricValue: '5',
    },
  },

  test6: {
    eventTriggerRepo: [
      {
        eventId: 'event1',
        boxId: 'box1',
        block: 'block1',
        height: 100,
        extractor: 'ext1',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx1',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '100',
        bridgeFee: '1',
        networkFee: '0.1',
        sourceChainTokenId: 'token1',
        sourceChainHeight: 100,
        targetChainTokenId: 'token2',
        sourceTxId: 'sourceTx1',
        sourceBlockId: 'sourceBlock1',
        spendBlock: 'block1',
        spendHeight: 110,
        spendTxId: 'spendTx1',
        result: 'successful',
        paymentTxId: 'paymentTx1',
        WIDsCount: 1,
        WIDsHash: 'hash1',
        serialized: '{}',
      },
      {
        eventId: 'event2',
        boxId: 'box2',
        block: 'block2',
        height: 101,
        extractor: 'ext2',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx2',
        fromAddress: 'addr2',
        toAddress: 'addr3',
        amount: '200',
        bridgeFee: '2',
        networkFee: '0.2',
        sourceChainTokenId: 'token3',
        sourceChainHeight: 101,
        targetChainTokenId: 'token4',
        sourceTxId: 'sourceTx2',
        sourceBlockId: 'sourceBlock2',
        spendBlock: 'block2',
        spendHeight: 115,
        spendTxId: 'spendTx2',
        result: 'successful',
        paymentTxId: 'paymentTx2',
        WIDsCount: 1,
        WIDsHash: 'hash2',
        serialized: '{}',
      },
      {
        eventId: 'event3',
        boxId: 'box3',
        block: 'block3',
        height: 102,
        extractor: 'ext3',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx3',
        fromAddress: 'addr3',
        toAddress: 'addr4',
        amount: '300',
        bridgeFee: '3',
        networkFee: '0.3',
        sourceChainTokenId: 'token5',
        sourceChainHeight: 102,
        targetChainTokenId: 'token6',
        sourceTxId: 'sourceTx3',
        sourceBlockId: 'sourceBlock3',
        spendBlock: 'block3',
        spendHeight: 120,
        spendTxId: 'spendTx3',
        result: 'successful',
        paymentTxId: 'paymentTx3',
        WIDsCount: 1,
        WIDsHash: 'hash3',
        serialized: '{}',
      },
      {
        eventId: 'event4',
        boxId: 'box4',
        block: 'block4',
        height: 103,
        extractor: 'ext4',
        fromChain: 'cardano',
        toChain: 'ergo',
        txId: 'tx4',
        fromAddress: 'addr4',
        toAddress: 'addr5',
        amount: '400',
        bridgeFee: '4',
        networkFee: '0.4',
        sourceChainTokenId: 'token7',
        sourceChainHeight: 103,
        targetChainTokenId: 'token8',
        sourceTxId: 'sourceTx4',
        sourceBlockId: 'sourceBlock4',
        spendBlock: 'block4',
        spendHeight: 113,
        spendTxId: 'spendTx4',
        result: 'fraud',
        paymentTxId: 'paymentTx4',
        WIDsCount: 1,
        WIDsHash: 'hash4',
        serialized: '{}',
      },
      {
        eventId: 'event5',
        boxId: 'box5',
        block: 'block5',
        height: 104,
        extractor: 'ext5',
        fromChain: 'cardano',
        toChain: 'ergo',
        txId: 'tx5',
        fromAddress: 'addr5',
        toAddress: 'addr6',
        amount: '500',
        bridgeFee: '5',
        networkFee: '0.5',
        sourceChainTokenId: 'token9',
        sourceChainHeight: 104,
        targetChainTokenId: 'token10',
        sourceTxId: 'sourceTx5',
        sourceBlockId: 'sourceBlock5',
        spendBlock: 'block5',
        spendHeight: 114,
        spendTxId: 'spendTx5',
        result: 'fraud',
        paymentTxId: 'paymentTx5',
        WIDsCount: 1,
        WIDsHash: 'hash5',
        serialized: '{}',
      },
      {
        eventId: 'event6',
        boxId: 'box6',
        block: 'block6',
        height: 105,
        extractor: 'ext6',
        fromChain: 'ethereum',
        toChain: 'ergo',
        txId: 'tx6',
        fromAddress: 'addr6',
        toAddress: 'addr7',
        amount: '600',
        bridgeFee: '6',
        networkFee: '0.6',
        sourceChainTokenId: 'token11',
        sourceChainHeight: 105,
        targetChainTokenId: 'token12',
        sourceTxId: 'sourceTx6',
        sourceBlockId: 'sourceBlock6',
        spendBlock: 'block6',
        spendHeight: 115,
        spendTxId: 'spendTx6',
        result: 'successful',
        paymentTxId: 'paymentTx6',
        WIDsCount: 1,
        WIDsHash: 'hash6',
        serialized: '{}',
      },
    ],
    expectedResults: {
      totalCount: 6,
      eventCounts: [
        {
          status: 'successful',
          fromChain: 'ergo',
          toChain: 'cardano',
          count: 3,
        },
        { status: 'fraud', fromChain: 'cardano', toChain: 'ergo', count: 2 },
        {
          status: 'successful',
          fromChain: 'ethereum',
          toChain: 'ergo',
          count: 1,
        },
      ],
      totalMetricValue: '6',
    },
  },
};

export const userEventTestData = {
  userEvent1: {
    fromAddress: 'addr1',
    toAddress: 'addr2',
    count: 5,
    lastProcessedHeight: 100,
  },

  userEvent2: {
    fromAddress: 'addr1',
    toAddress: 'addr3',
    count: 3,
    lastProcessedHeight: 150,
  },

  userEvent3: {
    fromAddress: 'addr2',
    toAddress: 'addr4',
    count: 2,
    lastProcessedHeight: 200,
  },

  userEvent4: {
    fromAddress: 'addr3',
    toAddress: 'addr5',
    count: 4,
    lastProcessedHeight: 180,
  },
};

export const userEventMetricTestData = {
  test1: {
    eventTriggerRepo: [
      {
        eventId: 'event1',
        boxId: 'box1',
        block: 'block1',
        height: 100,
        extractor: 'ext1',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx1',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '100',
        bridgeFee: '1',
        networkFee: '0.1',
        sourceChainTokenId: 'token1',
        sourceChainHeight: 100,
        targetChainTokenId: 'token2',
        sourceTxId: 'sourceTx1',
        sourceBlockId: 'sourceBlock1',
        spendBlock: 'block1',
        spendHeight: 110,
        spendTxId: 'spendTx1',
        result: 'successful',
        paymentTxId: 'paymentTx1',
        WIDsCount: 1,
        WIDsHash: 'hash1',
        serialized: '{}',
      },
      {
        eventId: 'event2',
        boxId: 'box2',
        block: 'block2',
        height: 101,
        extractor: 'ext2',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx2',
        fromAddress: 'addr1',
        toAddress: 'addr3',
        amount: '200',
        bridgeFee: '2',
        networkFee: '0.2',
        sourceChainTokenId: 'token3',
        sourceChainHeight: 101,
        targetChainTokenId: 'token4',
        sourceTxId: 'sourceTx2',
        sourceBlockId: 'sourceBlock2',
        spendBlock: 'block2',
        spendHeight: 115,
        spendTxId: 'spendTx2',
        result: 'successful',
        paymentTxId: 'paymentTx2',
        WIDsCount: 1,
        WIDsHash: 'hash2',
        serialized: '{}',
      },
      {
        eventId: 'event3',
        boxId: 'box3',
        block: 'block3',
        height: 102,
        extractor: 'ext3',
        fromChain: 'cardano',
        toChain: 'ergo',
        txId: 'tx3',
        fromAddress: 'addr2',
        toAddress: 'addr4',
        amount: '300',
        bridgeFee: '3',
        networkFee: '0.3',
        sourceChainTokenId: 'token5',
        sourceChainHeight: 102,
        targetChainTokenId: 'token6',
        sourceTxId: 'sourceTx3',
        sourceBlockId: 'sourceBlock3',
        spendBlock: 'block3',
        spendHeight: 120,
        spendTxId: 'spendTx3',
        result: 'successful',
        paymentTxId: 'paymentTx3',
        WIDsCount: 1,
        WIDsHash: 'hash3',
        serialized: '{}',
      },
      {
        eventId: 'event4',
        boxId: 'box4',
        block: 'block4',
        height: 103,
        extractor: 'ext4',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx4',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '400',
        bridgeFee: '4',
        networkFee: '0.4',
        sourceChainTokenId: 'token7',
        sourceChainHeight: 103,
        targetChainTokenId: 'token8',
        sourceTxId: 'sourceTx4',
        sourceBlockId: 'sourceBlock4',
        spendBlock: 'block4',
        spendHeight: 125,
        spendTxId: 'spendTx4',
        result: 'fraud',
        paymentTxId: 'paymentTx4',
        WIDsCount: 1,
        WIDsHash: 'hash4',
        serialized: '{}',
      },
    ],
    expectedResults: {
      totalCount: 3,
      userEvents: [
        { fromAddress: 'addr1', toAddress: 'addr2', count: 1 },
        { fromAddress: 'addr1', toAddress: 'addr3', count: 1 },
        { fromAddress: 'addr2', toAddress: 'addr4', count: 1 },
      ],
      totalMetricValue: '3',
    },
  },

  test2: {
    userEventRepo: [
      {
        fromAddress: 'addr1',
        toAddress: 'addr2',
        count: 5,
        lastProcessedHeight: 100,
      },
    ],
    metricRepo: [
      {
        key: 'user_event_total',
        value: '5',
        updatedAt: 1_000,
      },
    ],
    expectedResults: {
      totalCount: 0,
      userEvents: [{ fromAddress: 'addr1', toAddress: 'addr2', count: 5 }],
      totalMetricValue: '5',
    },
  },

  test3: {
    eventTriggerRepo: [
      {
        eventId: 'event1',
        boxId: 'box1',
        block: 'block1',
        height: 100,
        extractor: 'ext1',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx1',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '100',
        bridgeFee: '1',
        networkFee: '0.1',
        sourceChainTokenId: 'token1',
        sourceChainHeight: 100,
        targetChainTokenId: 'token2',
        sourceTxId: 'sourceTx1',
        sourceBlockId: 'sourceBlock1',
        spendBlock: 'block1',
        spendHeight: 110,
        spendTxId: 'spendTx1',
        result: 'successful',
        paymentTxId: 'paymentTx1',
        WIDsCount: 1,
        WIDsHash: 'hash1',
        serialized: '{}',
      },
      {
        eventId: 'event2',
        boxId: 'box2',
        block: 'block2',
        height: 101,
        extractor: 'ext2',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx2',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '200',
        bridgeFee: '2',
        networkFee: '0.2',
        sourceChainTokenId: 'token3',
        sourceChainHeight: 101,
        targetChainTokenId: 'token4',
        sourceTxId: 'sourceTx2',
        sourceBlockId: 'sourceBlock2',
        spendBlock: 'block2',
        spendHeight: 115,
        spendTxId: 'spendTx2',
        result: 'successful',
        paymentTxId: 'paymentTx2',
        WIDsCount: 1,
        WIDsHash: 'hash2',
        serialized: '{}',
      },
      {
        eventId: 'event3',
        boxId: 'box3',
        block: 'block3',
        height: 102,
        extractor: 'ext3',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx3',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '300',
        bridgeFee: '3',
        networkFee: '0.3',
        sourceChainTokenId: 'token5',
        sourceChainHeight: 102,
        targetChainTokenId: 'token6',
        sourceTxId: 'sourceTx3',
        sourceBlockId: 'sourceBlock3',
        spendBlock: 'block3',
        spendHeight: 120,
        spendTxId: 'spendTx3',
        result: 'successful',
        paymentTxId: 'paymentTx3',
        WIDsCount: 1,
        WIDsHash: 'hash3',
        serialized: '{}',
      },
    ],
    expectedResults: {
      totalCount: 3,
      userEvents: [{ fromAddress: 'addr1', toAddress: 'addr2', count: 3 }],
      totalMetricValue: '3',
    },
  },

  test4: {
    eventTriggerRepo: [
      {
        eventId: 'event1',
        boxId: 'box1',
        block: 'block1',
        height: 105,
        extractor: 'ext1',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx1',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '100',
        bridgeFee: '1',
        networkFee: '0.1',
        sourceChainTokenId: 'token1',
        sourceChainHeight: 105,
        targetChainTokenId: 'token2',
        sourceTxId: 'sourceTx1',
        sourceBlockId: 'sourceBlock1',
        spendBlock: 'block1',
        spendHeight: 115,
        spendTxId: 'spendTx1',
        result: 'successful',
        paymentTxId: 'paymentTx1',
        WIDsCount: 1,
        WIDsHash: 'hash1',
        serialized: '{}',
      },
      {
        eventId: 'event2',
        boxId: 'box2',
        block: 'block2',
        height: 106,
        extractor: 'ext2',
        fromChain: 'cardano',
        toChain: 'ergo',
        txId: 'tx2',
        fromAddress: 'addr2',
        toAddress: 'addr4',
        amount: '200',
        bridgeFee: '2',
        networkFee: '0.2',
        sourceChainTokenId: 'token3',
        sourceChainHeight: 106,
        targetChainTokenId: 'token4',
        sourceTxId: 'sourceTx2',
        sourceBlockId: 'sourceBlock2',
        spendBlock: 'block2',
        spendHeight: 116,
        spendTxId: 'spendTx2',
        result: 'successful',
        paymentTxId: 'paymentTx2',
        WIDsCount: 1,
        WIDsHash: 'hash2',
        serialized: '{}',
      },
    ],
    userEventRepo: [
      {
        fromAddress: 'addr1',
        toAddress: 'addr2',
        count: 5,
        lastProcessedHeight: 100,
      },
      {
        fromAddress: 'addr2',
        toAddress: 'addr4',
        count: 2,
        lastProcessedHeight: 100,
      },
    ],
    metricRepo: [
      {
        key: 'user_event_total',
        value: '7',
        updatedAt: 1_000,
      },
    ],
    expectedResults: {
      totalCount: 2,
      userEvents: [
        { fromAddress: 'addr1', toAddress: 'addr2', count: 6 }, // 5 + 1
        { fromAddress: 'addr2', toAddress: 'addr4', count: 3 }, // 2 + 1
      ],
      totalMetricValue: '9', // 7 + 2
    },
  },

  test5: {
    eventTriggerRepo: [
      {
        eventId: 'event1',
        boxId: 'box1',
        block: 'block1',
        height: 90,
        extractor: 'ext1',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx1',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '100',
        bridgeFee: '1',
        networkFee: '0.1',
        sourceChainTokenId: 'token1',
        sourceChainHeight: 90,
        targetChainTokenId: 'token2',
        sourceTxId: 'sourceTx1',
        sourceBlockId: 'sourceBlock1',
        spendBlock: 'block1',
        spendHeight: 95,
        spendTxId: 'spendTx1',
        result: 'successful',
        paymentTxId: 'paymentTx1',
        WIDsCount: 1,
        WIDsHash: 'hash1',
        serialized: '{}',
      },
    ],
    userEventRepo: [
      {
        fromAddress: 'addr1',
        toAddress: 'addr2',
        count: 5,
        lastProcessedHeight: 100,
      },
    ],
    metricRepo: [
      {
        key: 'user_event_total',
        value: '5',
        updatedAt: 1_000,
      },
    ],
    expectedResults: {
      totalCount: 0,
      userEvents: [{ fromAddress: 'addr1', toAddress: 'addr2', count: 5 }],
      totalMetricValue: '5',
    },
  },

  test6: {
    eventTriggerRepo: [
      {
        eventId: 'event1',
        boxId: 'box1',
        block: 'block1',
        height: 100,
        extractor: 'ext1',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx1',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '100',
        bridgeFee: '1',
        networkFee: '0.1',
        sourceChainTokenId: 'token1',
        sourceChainHeight: 100,
        targetChainTokenId: 'token2',
        sourceTxId: 'sourceTx1',
        sourceBlockId: 'sourceBlock1',
        spendBlock: 'block1',
        spendHeight: 110,
        spendTxId: 'spendTx1',
        result: 'successful',
        paymentTxId: 'paymentTx1',
        WIDsCount: 1,
        WIDsHash: 'hash1',
        serialized: '{}',
      },
      {
        eventId: 'event2',
        boxId: 'box2',
        block: 'block2',
        height: 101,
        extractor: 'ext2',
        fromChain: 'ergo',
        toChain: 'cardano',
        txId: 'tx2',
        fromAddress: 'addr1',
        toAddress: 'addr2',
        amount: '200',
        bridgeFee: '2',
        networkFee: '0.2',
        sourceChainTokenId: 'token3',
        sourceChainHeight: 101,
        targetChainTokenId: 'token4',
        sourceTxId: 'sourceTx2',
        sourceBlockId: 'sourceBlock2',
        spendBlock: 'block2',
        spendHeight: 115,
        spendTxId: 'spendTx2',
        result: 'successful',
        paymentTxId: 'paymentTx2',
        WIDsCount: 1,
        WIDsHash: 'hash2',
        serialized: '{}',
      },
      {
        eventId: 'event3',
        boxId: 'box3',
        block: 'block3',
        height: 102,
        extractor: 'ext3',
        fromChain: 'cardano',
        toChain: 'ergo',
        txId: 'tx3',
        fromAddress: 'addr2',
        toAddress: 'addr4',
        amount: '300',
        bridgeFee: '3',
        networkFee: '0.3',
        sourceChainTokenId: 'token5',
        sourceChainHeight: 102,
        targetChainTokenId: 'token6',
        sourceTxId: 'sourceTx3',
        sourceBlockId: 'sourceBlock3',
        spendBlock: 'block3',
        spendHeight: 120,
        spendTxId: 'spendTx3',
        result: 'successful',
        paymentTxId: 'paymentTx3',
        WIDsCount: 1,
        WIDsHash: 'hash3',
        serialized: '{}',
      },
      {
        eventId: 'event4',
        boxId: 'box4',
        block: 'block4',
        height: 103,
        extractor: 'ext4',
        fromChain: 'ethereum',
        toChain: 'ergo',
        txId: 'tx4',
        fromAddress: 'addr3',
        toAddress: 'addr5',
        amount: '400',
        bridgeFee: '4',
        networkFee: '0.4',
        sourceChainTokenId: 'token7',
        sourceChainHeight: 103,
        targetChainTokenId: 'token8',
        sourceTxId: 'sourceTx4',
        sourceBlockId: 'sourceBlock4',
        spendBlock: 'block4',
        spendHeight: 125,
        spendTxId: 'spendTx4',
        result: 'successful',
        paymentTxId: 'paymentTx4',
        WIDsCount: 1,
        WIDsHash: 'hash4',
        serialized: '{}',
      },
    ],
    expectedResults: {
      totalCount: 4,
      userEvents: [
        { fromAddress: 'addr1', toAddress: 'addr2', count: 2 },
        { fromAddress: 'addr2', toAddress: 'addr4', count: 1 },
        { fromAddress: 'addr3', toAddress: 'addr5', count: 1 },
      ],
      totalMetricValue: '4',
    },
  },
};

export const watcherConfig: WatcherCountConfig = {
  type: 'explorer',
  url: 'http://test-explorer.com',
  rwtTokenId: 'repoNFT',
  rwtNetworkMap: {
    ergo: 'rwt-ergo-token-id',
    cardano: 'rwt-cardano-token-id',
    ethereum: 'rwt-eth-token-id',
  },
};

export const mockBoxes = {
  ergoBox: {
    register_value: () => ({ to_i64: () => ({ to_str: () => '10' }) }),
    tokens: () => ({
      len: () => 1,
      get: () => ({
        id: () => ({
          to_str: () => 'rwt-ergo-token-id',
        }),
      }),
    }),
  } as unknown as any,

  cardanoBox: {
    register_value: () => ({ to_i64: () => ({ to_str: () => '20' }) }),
    tokens: () => ({
      len: () => 1,
      get: () => ({
        id: () => ({
          to_str: () => 'rwt-cardano-token-id',
        }),
      }),
    }),
  } as unknown as any,

  ethereumBox: {
    register_value: () => ({ to_i64: () => ({ to_str: () => '15' }) }),
    tokens: () => ({
      len: () => 1,
      get: () => ({
        id: () => ({
          to_str: () => 'rwt-eth-token-id',
        }),
      }),
    }),
  } as unknown as any,
};

export const watcherCountTestData = {
  test1: {
    boxes: [mockBoxes.ergoBox, mockBoxes.cardanoBox],
    watcherCountRepo: [],
    metricRepo: [],
    expectedResults: {
      networkCounts: [
        { network: 'ergo', count: 10 },
        { network: 'cardano', count: 20 },
      ],
      totalWatchers: 30,
    },
  },

  test2: {
    boxes: [mockBoxes.ergoBox, mockBoxes.cardanoBox],
    watcherCountRepo: [
      { network: 'ergo', count: 5 },
      { network: 'cardano', count: 8 },
    ],
    metricRepo: [{ key: 'watcher_count_total', value: '13', updatedAt: 1000 }],
    expectedResults: {
      networkCounts: [
        { network: 'ergo', count: 10 },
        { network: 'cardano', count: 20 },
      ],
      totalWatchers: 30,
    },
  },

  test3: {
    boxes: [mockBoxes.ergoBox, mockBoxes.cardanoBox, mockBoxes.ethereumBox],
    watcherCountRepo: [],
    metricRepo: [],
    expectedResults: {
      networkCounts: [
        { network: 'ergo', count: 10 },
        { network: 'cardano', count: 20 },
        { network: 'ethereum', count: 15 },
      ],
      totalWatchers: 45,
    },
  },
};
