logs:
  - type: console
    level: info
  - type: file
    path: ./logs/
    maxSize: 20m
    maxFiles: 14d
    level: info
    format: json
    createSymlink: true
db:
  logging: false
  useSSL: false
healthCheck:
  logging:
    maxErrors: 10
    maxWarns: 10
    duration: 100
  scanner:
    warnDiff: 2
    criticalDiff: 10
  updateInterval: 60
dataAggregator:
  interval: 60
tokenMap:
  onChainTokenMapEnabled: true
  path: config/tokensMap.json
statistics:
  lockedAssetsMetrics:
    interval: 86400
  generalMetrics:
    interval: 86400
  eventCountMetrics:
    interval: 86400
  userEventsMetric:
    interval: 86400
  watcherCountMetrics:
    interval: 86400
  bridgeFeeMetrics:
    interval: 86400
  bridgeAmountMetrics:
    interval: 86400
chains:
  ergo:
    scanInterval: 120
    method: explorer
    explorer:
      connections:
        - url: https://api.ergoplatform.com/
    blockCleanupActive: false
  cardano:
    active: false
    scanInterval: 30
    koios:
      connections:
        - url: https://api.koios.rest/api/v1/
          timeout: 100
    blockCleanupActive: true
  bitcoin:
    active: false
    scanInterval: 600
    blockCleanupActive: true
  bitcoin-runes:
    active: false
    unisatUrl: https://open-api.unisat.io
  doge:
    active: false
    scanInterval: 60
    adapter:
      blockCypher:
        url: https://api.blockcypher.com
    blockCleanupActive: true
  ethereum:
    active: false
    scanInterval: 60
    blockCleanupActive: true
  binance:
    active: false
    scanInterval: 10
    blockCleanupActive: true
  firo:
    active: false
    scanInterval: 60
    blockCleanupActive: true
  handshake:
    active: false
    scanInterval: 600
    blockCleanupActive: true
commitmentExtractor:
  active: false
eventTriggerExtractor:
  active: false
paths:
  contracts: config/contracts.json
  healthReport: healthReport.json
