redis:
  address: http://kv
  token: 'kv-token'
chains:
  binance:
    adapter:
      chunkSize: 1
  ethereum:
    adapter:
      chunkSize: 1
tokenMap:
  onChainTokenMapEnabled: false
  path: tests/config/tokensMap.json
paths:
  contracts: tests/config/contracts.json
